name: "Deploy to Pages"
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and Build
        run: |
          yarn
          yarn gulp build
          yarn build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: storybook-static
      - name: Publish to dist
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Deploy to dist"
          branch: main
          file_pattern: dist/*
