name: "Publish Assets"
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install and Build
        run: |
          yarn
          yarn gulp build
      - name: Build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-directory
          path: dist
      - name: Publish
        run: yarn gulp publish
