name: "Publish Assets"
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile and Publish
        run: |
          yarn
          yarn gulp publish
